ops/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import home_view
from .views_login import login_view
from .views_logout import logout_view

urlpatterns = [
    path('', home_view, name='home'),
    path('login', login_view, name='login'),
    path('logout', logout_view, name='logout'),

    path('server/', include('server.urls')),
    path('node/', include('node.urls')),
    path('task/', include('task.urls')),
    path('version/', include('version.urls')),

    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task/urls.py
from django.urls import path

from .views import home_view
from .views_add import add_view
from .views_edit import edit_view

app_name = 'task'
urlpatterns = [
    path('', home_view, name='home'),
    path('add/', add_view, name='add'),
    path('<int:task_id>/edit/', edit_view, name='edit'),
]

task/models.py
from django.db import models


class Task(models.Model):
    TYPE_CHOICES = (
        (0, 'Template'),
        (1, 'Task'),
    )

    type = models.SmallIntegerField(choices=TYPE_CHOICES, default=0)
    name = models.CharField(max_length=255)
    code = models.CharField(max_length=255, db_index=True)

    text = models.TextField()

    datetime_update = models.DateTimeField(auto_now=True, db_index=True)
    datetime_create = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-datetime_update']

    def __str__(self):
        return self.code


class History(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)

    text = models.TextField()
    datetime_create = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ['-datetime_create']


class Parameter(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)

    content_type = models.ForeignKey('contenttypes.ContentType', on_delete=models.CASCADE)
    field = models.CharField(max_length=255)

    sort = models.SmallIntegerField(default=0, db_index=True)

    class Meta:
        ordering = ['sort']


class Log(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)

    args = models.TextField()
    result = models.TextField()
    status = models.CharField(max_length=255)

    datetime_create = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ['-datetime_create']

task/forms.py
from django import forms

from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('name', 'code', 'text')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            t = self.fields[field].widget.__class__.__name__
            if t != 'CheckboxInput':
                self.fields[field].widget.attrs['class'] = 'form-control'
            self.fields[field].widget.attrs['type'] = t
        self.fields['text'].widget.attrs['rows'] = '24'

task/views.py
from django.shortcuts import render

from utils.decorators import permission_required
from .models import Task


@permission_required(['task.add_task', 'task.change_task', 'task.delete_task'], raise_exception=True)
def home_view(request):
    task_list = Task.objects.filter(type=1)
    return render(
        request,
        'task/home.html',
        {
            'NAV': 'task',
            'task_list': task_list,
        }
    )

task/templates/task/add.html
{% extends "base.html" %}

{% block content %}
  <form action="" method="post">{% csrf_token %}
    <div class="form-group">
      <label for="template">Template</label>
      <select class="form-control" id="template" name="task">
        <option value="0">Empty</option>
        {% for task in task_list %}
        <option value="{{ task.id }}">{{ task.name }}</option>
        {% endfor %}
      </select>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{% endblock %}

task/templates/task/edit.html
{% extends "base.html" %}

{% block content %}
  {% include "form.html" with form=form %}
{% endblock %}

task/templates/task/home.html
{% extends "base.html" %}

{% block content %}
  <div class="row">
    <div class="col align-self-end">
      <div class="float-right">
        <a href="{% url 'task:add' %}" class="btn btn-success btn-sm">Add</a>
      </div>
    </div>
  </div>
  <table class="table table-hover table-sm">
    <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Code</th>
      <th scope="col">Update</th>
      <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    {% for task in task_list %}
    <tr>
      <th scope="row">{{ task.id }}</th>
      <td>{{ task.name }}</td>
      <td><span class="badge badge-pill badge-info">{{ task.code }}</span></td>
      <td>{{ task.datetime_update }}</td>
      <td><a href="{% url 'task:edit' task.id %}" class="btn btn-secondary btn-sm">Edit</a></td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock %}