node/urls.py
from django.urls import path

from .views import home_view
from .views_detail import detail_view

app_name = 'node'
urlpatterns = [
    path('', home_view, name='home'),
    path('<int:node_id>/', detail_view, name='detail'),
]

ops/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import home_view
from .views_login import login_view
from .views_logout import logout_view

urlpatterns = [
    path('', home_view, name='home'),
    path('login', login_view, name='login'),
    path('logout', logout_view, name='logout'),

    path('server/', include('server.urls')),
    path('node/', include('node.urls')),
    path('task/', include('task.urls')),
    path('version/', include('version.urls')),

    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/urls.py
from django.urls import path

from .views import home_view

app_name = 'server'
urlpatterns = [
    path('', home_view, name='home'),
]

task/urls.py
from django.urls import path

from .views import home_view
from .views_add import add_view
from .views_edit import edit_view

app_name = 'task'
urlpatterns = [
    path('', home_view, name='home'),
    path('add/', add_view, name='add'),
    path('<int:task_id>/edit/', edit_view, name='edit'),
]

node/models.py
from django.db import models


class Node(models.Model):
    STATUS_CHOICES = (
        (-3, 'Deleted'),
        (-2, 'Waiting Delete'),
        (-1, 'Pause'),
        (0, 'Waiting'),
        (1, 'Pending'),
        (2, 'Live'),
    )

    server = models.ForeignKey('server.Server', null=True, on_delete=models.SET_NULL)
    docker_compose = models.ForeignKey('docker.Compose', null=True, blank=True, on_delete=models.SET_NULL)

    name = models.CharField(max_length=255)
    code = models.CharField(max_length=120, db_index=True)
    url = models.CharField(max_length=255)

    path = models.CharField(max_length=255)
    port = models.CharField(max_length=120)
    tag = models.CharField(max_length=255)

    sort = models.IntegerField(default=0, db_index=True)
    status = models.SmallIntegerField(choices=STATUS_CHOICES, default=0)

    datetime_update = models.DateTimeField(auto_now=True)
    datetime_create = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['sort']

    def __str__(self):
        return self.name


class Log(models.Model):
    TYPE_CHOICES = (
        (1, 'develop'),
        (2, 'business'),
    )

    STATUS_CHOICES = (
        (-1, 'Failed'),
        (0, 'Waiting'),
        (1, 'Running'),
        (2, 'Completed'),
    )

    node = models.ForeignKey(Node, on_delete=models.CASCADE)

    type = models.SmallIntegerField(choices=TYPE_CHOICES)
    title = models.CharField(max_length=255)
    message = models.TextField()
    status = models.SmallIntegerField(choices=STATUS_CHOICES)

    datetime_create = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ['-datetime_create']

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Ops</title>

  <link href="{% static 'bootstrap-5.2.0-beta1/css/bootstrap.min.css' %}" rel="stylesheet">
</head>

<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">Ops</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item {% if NAV == 'home' %}active{% endif %}">
          <a class="nav-link" href="{% url 'home' %}">Home</a>
        </li>
        {% if perms.server.add_server or perms.server.change_server or perms.server.delete_server %}
          <li class="nav-item {% if NAV == 'server' %}active{% endif %}">
            <a class="nav-link" href="{% url 'server:home' %}">Server</a>
          </li>
        {% endif %}
        {% if perms.node.add_node or perms.node.change_node or perms.node.delete_node %}
          <li class="nav-item {% if NAV == 'node' %}active{% endif %}">
            <a class="nav-link" href="{% url 'node:home' %}">Node</a>
          </li>
        {% endif %}
        {% if perms.task.add_task or perms.task.change_task or perms.task.delete_task %}
          <li class="nav-item {% if NAV == 'task' %}active{% endif %}">
            <a class="nav-link" href="{% url 'task:home' %}">Task</a>
          </li>
        {% endif %}
      </ul>
    </div>

    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
      </li>
    </ul>
  </div>
</nav>

<main role="main">
  <div class="container">
    <br/><br/><br/>
    {% block content %}
    {% endblock %}
  </div>
</main>

<script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
<script src="{% static 'bootstrap-5.2.0-beta1/js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/form.html
<form action="" method="post"> {% csrf_token %}
  {% for field in form %}
    {% if field.field.widget.attrs.type == "CheckboxInput" %}
      <div class="checkbox">
        <label>
          {{ field }} {{ field.label }}
        </label>
      </div>
    {% else %}
      <fieldset class="form-group {% if field.errors %}has-danger{% endif %}">
        <label class="form-control-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field }}
        {% for error in field.errors %}
          <small class="text-help">{{ error }}</small>
        {% endfor %}
        <small class="text-muted">{{ field.help_text }}</small>
      </fieldset>
    {% endif %}
  {% endfor %}
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

templates/home.html
{% extends "base.html" %}

templates/login.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Ops: Login</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/login.css' %}" rel="stylesheet">
  </head>

  <body>

    <div class="container">
      {% if message != None %}
        <div class="alert alert-danger" role="alert">
          {{ message }}
        </div>
      {% endif %}
      <form class="form-signin" method="post">{% csrf_token %}
        <h2 class="form-signin-heading">Please Login in</h2>
        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="text" name="username" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
      </form>

    </div>
  </body>
</html>

templates/pagination.html
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center pagination-sm">
    {% if content_list.has_previous %}
      <li class="page-item ">
        <a class="page-link" href="?page={{ content_list.previous_page_number }}{% if q %}{{ q }}{% endif %}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Previous</span>
        </a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Previous</span>
        </a>
      </li>
    {% endif %}

    {% for page in content_list.paginator.page_range %}
      <li class="page-item {% if page == content_list.number %}active{% endif %}">
        <a class="page-link" href="?page={{ page }}{% if q %}{{ q }}{% endif %}">{{ page }}</a>
      </li>
    {% endfor %}

    {% if content_list.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ content_list.next_page_number }}{% if q %}{{ q }}{% endif %}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Next</span>
        </a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Next</span>
        </a>
      </li>
    {% endif %}
  </ul>
</nav>