node/urls.py
from django.urls import path

from .views import home_view
from .views_detail import detail_view

app_name = 'node'
urlpatterns = [
    path('', home_view, name='home'),
    path('<int:node_id>/', detail_view, name='detail'),
]

ops/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import home_view
from .views_login import login_view
from .views_logout import logout_view

urlpatterns = [
    path('', home_view, name='home'),
    path('login', login_view, name='login'),
    path('logout', logout_view, name='logout'),

    path('server/', include('server.urls')),
    path('node/', include('node.urls')),
    path('task/', include('task.urls')),
    path('version/', include('version.urls')),

    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

node/models.py
from django.db import models


class Node(models.Model):
    STATUS_CHOICES = (
        (-3, 'Deleted'),
        (-2, 'Waiting Delete'),
        (-1, 'Pause'),
        (0, 'Waiting'),
        (1, 'Pending'),
        (2, 'Live'),
    )

    server = models.ForeignKey('server.Server', null=True, on_delete=models.SET_NULL)
    docker_compose = models.ForeignKey('docker.Compose', null=True, blank=True, on_delete=models.SET_NULL)

    name = models.CharField(max_length=255)
    code = models.CharField(max_length=120, db_index=True)
    url = models.CharField(max_length=255)

    path = models.CharField(max_length=255)
    port = models.CharField(max_length=120)
    tag = models.CharField(max_length=255)

    sort = models.IntegerField(default=0, db_index=True)
    status = models.SmallIntegerField(choices=STATUS_CHOICES, default=0)

    datetime_update = models.DateTimeField(auto_now=True)
    datetime_create = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['sort']

    def __str__(self):
        return self.name


class Log(models.Model):
    TYPE_CHOICES = (
        (1, 'develop'),
        (2, 'business'),
    )

    STATUS_CHOICES = (
        (-1, 'Failed'),
        (0, 'Waiting'),
        (1, 'Running'),
        (2, 'Completed'),
    )

    node = models.ForeignKey(Node, on_delete=models.CASCADE)

    type = models.SmallIntegerField(choices=TYPE_CHOICES)
    title = models.CharField(max_length=255)
    message = models.TextField()
    status = models.SmallIntegerField(choices=STATUS_CHOICES)

    datetime_create = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ['-datetime_create']

node/views.py
from django.shortcuts import render

from server.models import Server
from utils.decorators import permission_required
from utils.paginator import listing, get_q
from .models import Node


@permission_required(['node.add_node', 'node.change_node', 'node.delete_node'], raise_exception=True)
def home_view(request):
    node_list = Node.objects.select_related('server').all()
    try:
        q_server = int(request.GET.get('q_server', None))
    except:
        q_server = None

    if q_server and q_server > 0:
        try:
            q_server = int(q_server)
            node_list = node_list.filter(server_id=q_server)
        except:
            pass

    node_list = listing(request, node_list)
    server_list = Server.objects.all()

    return render(
        request,
        'node/home.html',
        {
            'NAV': 'node',
            'node_list': node_list,
            'server_list': server_list,
            'q_server': q_server,
            'q_paginator': get_q({
                'q_server': q_server
            })
        }
    )

node/templates/node/detail.html
{% extends "base.html" %}

{% block content %}
  {% for task in task_list %}
    <div class="card">
      <div class="card-header">
        {{ task.name }} <span class="badge badge-pill badge-info">{{ task.code }}</span>
      </div>
      <div class="card-body">
        <h5 class="card-title">Special title treatment</h5>
        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
        <a href="#" class="btn btn-primary">Execute</a>
      </div>
    </div>
  {% endfor %}
  <table class="table table-hover table-sm">
    <thead>
    <tr class="text-center">
      <th scope="col">#</th>
      <th scope="col">Type</th>
      <th scope="col">Title</th>
      <th scope="col">Status</th>
      <th scope="col">TimeStamp</th>
      <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    {% for log in log_list %}
      <tr class="text-center">
        <th scope="row">{{ log.id }}</th>
        <td>{{ log.get_type_display }}</td>
        <td class="text-left">{{ log.title }}</td>
        <td>{{ node.datetime_create }}</td>
        <td>
          <a href="#" class="btn btn-sm btn-secondary">Detail</a>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  {% include "pagination.html" with content_list=log_list q=q_paginator %}
{% endblock %}

node/templates/node/home.html
{% extends "base.html" %}

{% block content %}
  <div class="row">
    <div class="col align-self-end">
      <form method="get">
        <div class="form-row align-items-center float-right">
          <div class="col-auto my-1">
            <select class="custom-select mr-sm-2" name="q_server">
              <option value="0">All Server</option>
              {% for server in server_list %}
                <option value="{{ server.id }}" {% if q_server == server.id %}selected{% endif %}>
                  {{ server.name }}
                </option>
              {% endfor %}
            </select>
          </div>
          <div class="col-auto my-1">
            <button type="submit" class="btn btn-primary btn-sm">Filter</button>
          </div>
        </div>
      </form>
    </div>
  </div>
  <table class="table table-hover table-sm">
    <thead>
    <tr class="text-center">
      <th scope="col">#</th>
      <th scope="col">Server</th>
      <th scope="col">Name</th>
      <th scope="col">URL</th>
      <th scope="col">Port / Tag</th>
      <th scope="col">Status</th>
      <th scope="col">Update / <small>Create</small></th>
      <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    {% for node in node_list %}
      <tr class="text-center">
        <th scope="row">{{ node.id }}</th>
        <td class="text-left">
          {% if node.server.image %}
            <img src="{{ node.server.image.url }}" width="45" class="rounded">
          {% endif %}
          <span class="badge badge-pill badge-success">{{ node.server.name }}</span>
        </td>
        <td>{{ node.name }} <br/> <span class="badge badge-pill badge-info">{{ node.code }}</span></td>
        <td class="text-left"><a href="{{ node.url }}" target="_blank">{{ node.url }}</a></td>
        <td>{{ node.port }} / <span class="badge badge-pill badge-primary">{{ node.tag }}</span></td>
        <td>{{ node.get_status_display }}</td>
        <td>{{ node.datetime_update }} <br/>
          <small>{{ node.datetime_create }}</small>
        </td>
        <td>
          <a href="{% url 'node:detail' node.id %}" class="btn btn-sm btn-secondary">Detail</a>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  {% include "pagination.html" with content_list=node_list q=q_paginator %}
{% endblock %}